name: automerge
on:
  pull_request:
    types:
      - labeled
      - opened
  check_suite:
    types: [completed]
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MERGE_LABELS: "automerge"
      - name: feedback
        if: steps.automerge.outputs.mergeResult == "merged"
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ github.token }}
          repo-token-user-login: 'github-actions[bot]'

          message: |
            ${{ steps.automerge.outputs.mergeResult }}

