name: Automerge
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled

  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull request number
        required: false

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true


