name: Plan / Apply on Merge
on:
  push:
    branches: [main, development, staging]

jobs:
  inform_about_apply:
    name: Inform about apply
    runs-on: macos-latest
    steps:
      - name: Inform on PR that Apply is Running
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ***Running terraform apply***
            Results will display here momentarily...
